username: admin
password: admin
insecure: true
encoding: json_ietf
log: true

targets:
  # Add targets configuration here
  # e.g:
  # 192.168.1.131:57400:
  #   username: gnmic
  #   password: secret_password


subscriptions:
  # Add subscriptions configuration here
  # e.g:
  # sub1:
  #   paths:
  #     - /interface/statistics
  #   stream-mode: sample
  #   sample-interval: 1s

outputs:
  prom-output:
    type: prometheus
    listen: "gnmic1:9804"
    service-registration:
      address: consul-agent:8500
