username: admin
password: admin
skip-verify: true
encoding: json_ietf
log: true

loader:
  type: docker
  filters:
    - containers:
      - label=clab-node-kind: srl
        label=containerlab: lab23
      config:
        outputs:
          - nats-output
          
subscriptions:
  # Add subscriptions configuration here
  # e.g:
  sub1:
    paths:
      - /interface/statistics
    stream-mode: sample
    sample-interval: 10s

# clustering config
clustering:
  cluster-name: cluster2
  targets-watch-timer: 30s
  locker:
    type: consul
    address: clab-lab23-consul-agent:8500

inputs:
  nats-input:
    type: nats
    address: clab-lab23-nats:4222
    subject: telemetry
    outputs:
      - output1

outputs:
  nats-output:
    type: nats
    address: clab-lab23-nats:4222
    subject: telemetry

  output1:
    type: prometheus
    service-registration:
      address: clab-lab23-consul-agent:8500
      use-lock: true
