log: true

inputs:
  nats-input:
    type: nats
    address: nats:4222
    subject: telemetry
    outputs:
      - prom-output

outputs:
  prom-output:
    type: prometheus
    listen: "gnmic-relay:9804"
    service-registration:
      address: consul-agent:8500
