username: admin
password: admin
insecure: true
encoding: json_ietf
log: true

targets:
  # Add targets configuration here
  # e.g:
  # 192.168.1.131:57400:
  #   username: gnmic
  #   password: secret_password


subscriptions:
  # Add subscriptions configuration here
  # e.g:
  # sub1:
  #   paths:
  #     - /interface/statistics
  #   stream-mode: sample
  #   sample-interval: 1s

outputs:
  file-output:
    type: file
    filename: /app/file-out.txt
    
  prom-output:
    type: prometheus
    listen: "gnmic1:9804"
    service-registration:
      address: consul-agent:8500

  influxdb-output:
    type: influxdb
    url: http://influxdb:8086
    bucket: telemetry # db name
    token: gnmic:gnmic # username:password
    batch-size: 1000
    flush-timer: 10s
  
  kafka-output:
    type: kafka
    address: kafka-server:9092
    topic: telemetry
  
  nats-output:
    type: nats
    address: nats:4222
    subject: telemetry