log: true

inputs:
  nats-input:
    type: input
    address: nats:4222
    subject: telemetry
    outputs:
      - prom-output

outputs:
  output1:
    type: prometheus
    service-registration:
      address: consul-agent:8500
      use-lock: true
