username: admin
password: admin
skip-verify: true
encoding: json_ietf
log: true

loader:
  type: docker
  filters:
    - containers:
      - label=clab-node-kind: srl
        label=containerlab: lab22

subscriptions:
  # Add subscriptions configuration here
  # e.g:
  sub1:
    paths:
      - /interface/statistics
    stream-mode: sample
    sample-interval: 10s

api-server:
  enable-metrics: true
  
# clustering config
clustering:
  cluster-name: cluster2
  targets-watch-timer: 30s
  locker:
    type: consul
    address: clab-lab22-consul-agent:8500

outputs:
  output1:
    type: prometheus
    service-registration:
      address: clab-lab22-consul-agent:8500
