username: admin
password: admin
skip-verify: true
encoding: json_ietf
log: true

loader:
  type: docker
  filters:
    - containers:
      - label=clab-node-kind: srl
        label=containerlab: lab33b
      config:
        outputs:
          - nats-output
          
subscriptions:
  # Add subscriptions configuration here
  # e.g:
  sub1:
    paths:
      - /interface/statistics
    stream-mode: sample
    sample-interval: 10s

# clustering config
clustering:
  cluster-name: cluster2
  targets-watch-timer: 30s
  locker:
    type: consul
    address: clab-lab33b-consul-agent:8500

outputs:
  nats-output:
    type: nats
    address: clab-lab33b-nats:4222
    subject: telemetry

