apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: InfluxDB
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    url: http://clab-lab15-prometheus:9090
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    version: 1
    editable: true

  - name: InfluxDB
    type: influxdb
    orgId: 1
    url: http://clab-lab15-influxdb:8086
    user: gnmic
    password: gnmic
    database: telemetry
    editable: true