username: admin
password: admin
insecure: true
encoding: json_ietf
log: true

# clustering config
clustering:
  cluster-name: cluster1
  targets-watch-timer: 30s
  locker:
    type: consul
    address: consul-agent:8500

targets:
  # Add targets configuration here
  # e.g:
  # 192.168.1.131:57400:
  #   username: gnmic
  #   password: secret_password
  #   outputs:
  #     - nats-output


subscriptions:
  # Add subscriptions configuration here
  # e.g:
  # sub1:
  #   paths:
  #     - /interface/statistics
  #   stream-mode: sample
  #   sample-interval: 1s

inputs:
  nats-input:
    type: nats
    address: nats:4222
    subject: telemetry
    outputs:
      - output1

outputs:
  nats-output:
    type: nats
    address: nats:4222
    subject: telemetry

  output1:
    type: prometheus
    service-registration:
      address: consul-agent:8500
      use-lock: true
