name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - "docs-*"
    tags:
      - "v*"

env:
  MKDOCS_MATERIAL_VER: 7.2.8

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v $(pwd):/docs --entrypoint mkdocs squidfunk/mkdocs-material:${MKDOCS_MATERIAL_VER} gh-deploy --force --strict
