---
name: release
on:
  push:
    tags:
      - v*
env:
  GOVER: 1.17.2
  GORELEASER_VER: v0.180.3

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
      - run: go test -cover ./...
        env:
          CGO_ENABLED: 0

  release:
    runs-on: ubuntu-20.04
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}

      - name: Install upx
        run: sudo apt update && sudo apt install -y libucl1 && curl -L http://archive.ubuntu.com/ubuntu/pool/universe/u/upx-ucl/upx-ucl_3.96-2_amd64.deb -o /tmp/upx.deb && sudo dpkg -i /tmp/upx.deb

      - name: Login to dockerhub
        run: docker login -u vikar2 -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to github container registry
        run: docker login ghcr.io -u karimra -p ${{ secrets.GHCR_TOKEN }}

      - name: Release with goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: ${{ env.GORELEASER_VER }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
